### ISSUE TITLE
[RFC] Consider some renamings

### ISSUE THREAD

**Issue by wouterj** [hostnet/form-handler-component#12]
This issue ask for quite a big change, but I just wanted to share my thoughts about this cool package. It's quite hard to grasp at first and I think naming is part of this.

The name that confused me most is the `FormProviderInterface`. It doesn't actually provide anything, you pass the handler (and optionally the form) to it. In fact, this is the actual _form handler_.

On the other hand, `FormHandlerInterface` isn't about handling at all (it's delegated to both `FormProviderInterface` and `FormSuccesHandlerInterface`/`FormFailureHandlerInterface`). In fact, this interface is more about _providing the form_. It's more like a form manager or the like.

I think renaming these, especially the `FormProviderInterface` could help in understanding the responsibilities of the classes.

_Please note that I'm just starting with this bundle. Maybe the names do make lots of sense and I just don't understand the internals good enough yet._

**Comment by iltar** [comment]
I think you're on the right tracks:
```php
// current situation
fooAction(RegistrationFormHandler $handler)
    FormProvider::handle($handler)
```

```php
// proposed situation
fooAction(RegistrationFormManager $manager)
    FormHandler::handle($manager)
```

While I'm not sure if Manager is the right name, it does make more sense like this as the handler will handle things looking at it from an action perspective. I think the success/failure interfaces can simply stay as they are. 

@nicoschoenmaker do you feel like throwing in same names in here as you're usually against `Manager`?

**Comment by nicoschoenmaker** [comment]
:+1: on renaming `FormProvider` to `FormHandler`.

Provided we find a different name for this guy:
```
interface FormHandlerInterface
{
    public function getType();
    public function getData();
    public function getOptions();
    public function getForm();
    public function setForm(FormInterface $form);
}
```

If it wouldn't have the `setForm` function, then I would consider `FormProvider` a good name for it.

Why is `setForm` needed? Because if I also implement `FormSuccesHandlerInterface` (or failure), then it's nice to have a pointer to the form. So why not pass it as an argument to `onSuccess`?

*Wouldn't switching these two names be really akward for existing users of the component?*

**Comment by iltar** [comment]
> Why is setForm needed? Because if I also implement FormSuccesHandlerInterface (or failure), then it's nice to have a pointer to the form. So why not pass it as an argument to onSuccess?

Mainly because of this: https://github.com/hostnet/form-handler-component/blob/master/src/Simple/SimpleFormProvider.php#L61

Afterwards this form is required to be created via `$handler->getForm()->createView()`. Maybe we could replace that with a delegator and have the handler (`SimpleFormProvider`) store the forms instead, could even get rid of `getForm()` in the current form handlers:

```php
if (($response = $this->form_handler->handle($provider)) instanceof Response) {
    return $response;
}

return [
    'form' => $this->form_handler->createView($provider),
];

interface FormTypeProviderInterface
{
    public function getType();
    public function getData();
    public function getOptions();
}
```

**Comment by yannickl88** [comment]
Note sure if I like to name `FormManager` for the (current) FormHandlers. I much more prefer `Wrapper` or  something that implies a bit more state. Moreover, if I have multiple handlers for the same form type (which can occur, and has in our codebase), having multiple managers seems very confusing.

```php
terminateAction(CancelFormManager $cancel_manager, CancelFormManager $trade_manager)
{
    // ...
}
```

While I agree with @nicoschoenmaker and @iltar that `::setForm()` and `::getForm()` can possibly removed I would suggest another RFC since else this might get too big.

**Comment by yannickl88** [comment]
With https://github.com/hostnet/form-handler-component/pull/17 names should be a bit more clean in the new namespace.

**Comment by yannickl88** [comment]
closing due to PR #17 being merged.
